# This is a basic workflow to help you get started with Actions

name: Model Train

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          TB_CREDENTIALS: ${{ secrets.TB_CREDENTIALS }}
        run: |
          pip install -r requirements.txt
          pip install .
          
          cd tests && wget ${{ secrets.DATA_PATH }} && python train_morphine_model.py
          
          # write CML report
          cml-tensorboard-dev --logdir tests/lightning_logs --md --name "Go to tensorboard" >> report.md
          cml-send-comment report.md
          
          
